FactoryGirl.define do
  factory :user do
    sequence(:username) { |n| "User_#{n}" }
    first_name "James"
    last_name "Brown"
    country
    latitude "52.417"
    longitude "16.883"
    sequence(:email) { |n| "user_#{n}@homeschooling.com" }
    password "foobar12"
    password_confirmation "foobar12"
    change_password_needed false


    factory :user_facebook_auth do |u|
      password "autogenerated_by_system"
      password_confirmation "autogenerated_by_system"
      latitude nil
      longitude nil
      change_password_needed true
      country_id nil

      u.after(:create) do |user|
        user.o_auth_credentials << FactoryGirl.create(:facebook_credential)
      end

      factory :user_facebook_valid_profile do |u|
        latitude "52.417"
        longitude "16.883"
        country_id 1
      end
    end
  end
end
