language: ruby
rvm:
  - 2.0.0
script:
  - bundle exec rake db:migrate
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database homeschooling_test;' -U postgres